server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    wait-time-in-ms-when-sync-empty: 1
  serviceUrl:
    defaultZone: http://localhost:${server.port}/eureka/


